module.exports = {

  us: [
    '%s@email.uscc.net',
    '%s@message.alltel.com',
    '%s@messaging.sprintpcs.com',
    '%s@mobile.celloneusa.com',
    '%s@msg.telus.com',
    '%s@paging.acswireless.com',
    '%s@pcs.rogers.com',
    '%s@qwestmp.com',
    '%s@sms.ntwls.net',
    '%s@tmomail.net',
    '%s@txt.att.net',
    '%s@txt.windmobile.ca',
    '%s@vtext.com',
    '%s@text.republicwireless.com',
    '%s@msg.fi.google.com',

    // '%s@message.ting.com', // Duplicate of Sprint
    // '%s@sms.edgewireless.com',  // slow
  ],

  canada: [
    '%s@blueskyfrog.com',
    '%s@bplmobile.com',
    '%s@cellularonewest.com',
    '%s@clearlydigital.com',
    '%s@comcastpcs.textmsg.com',
    '%s@corrwireless.net',
    '%s@csouth1.com',
    '%s@cwemail.com',
    '%s@cwwsms.com',
    '%s@email.swbw.com',
    '%s@email.uscc.net',
    '%s@fido.ca',
    '%s@ideacellular.net',
    '%s@inlandlink.com',
    '%s@ivctext.com',
    '%s@message.alltel.com',
    '%s@messaging.centurytel.net',
    '%s@messaging.sprintpcs.com',
    '%s@mobile.celloneusa.com',
    '%s@mobile.dobson.net',
    '%s@mobile.surewest.com',
    '%s@mobilecomm.net',
    '%s@msg.clearnet.com',
    '%s@msg.koodomobile.com',
    '%s@msg.telus.com',
    '%s@my2way.com',
    '%s@myboostmobile.com',
    '%s@onlinebeep.net',
    '%s@page.metrocall.com',
    '%s@pagemci.com',
    '%s@paging.acswireless.com',
    '%s@pcs.rogers.com',
    '%s@pcsone.net',
    '%s@qwestmp.com',
    '%s@satellink.net',
    '%s@sms.3rivers.net',
    '%s@sms.bluecell.com',
    '%s@sms.edgewireless.com',
    '%s@sms.goldentele.com',
    '%s@sms.pscel.com',
    '%s@sms.wcc.net',
    '%s@text.houstoncellular.net',
    '%s@text.mtsmobility.com',
    '%s@tmomail.net',
    '%s@tms.suncom.com',
    '%s@txt.att.net',
    '%s@txt.bell.ca',
    '%s@txt.northerntelmobility.com',
    '%s@txt.windmobile.ca',
    '%s@uswestdatamail.com',
    '%s@utext.com',
    '%s@vmobile.ca',
    '%s@vmobl.com',
    '%s@vtext.com',
  ],

  intl: [
    '%s@airtelchennai.com',
    '%s@airtelkol.com',
    '%s@airtelmail.com',
    '%s@alphame.com',
    '%s@bluewin.ch',
    '%s@bplmobile.com',
    '%s@c.vodafone.ne.jp',
    '%s@celforce.com',
    '%s@correo.movistar.net',
    '%s@delhi.hutch.co.in',
    '%s@digitextjm.com',
    '%s@e-page.net',
    '%s@escotelmobile.com',
    '%s@freesurf.ch',
    '%s@gsm1800.telia.dk',
    '%s@h.vodafone.ne.jp',
    '%s@ideacellular.net',
    '%s@itelcel.com',
    '%s@m1.com.sg',
    '%s@ml.bm',
    '%s@mmail.co.uk',
    '%s@mobilpost.no',
    '%s@mobistar.be',
    '%s@mobtel.co.yu',
    '%s@movistar.net',
    '%s@msgnextel.com.mx',
    '%s@msg.globalstarusa.com',
    '%s@msg.iridium.com',
    '%s@mujoskar.cz',
    '%s@mymeteor.ie',
    '%s@mysmart.mymobile.ph',
    '%s@mysunrise.ch',
    '%s@o2.co.uk',
    '%s@o2imail.co.uk',
    '%s@onemail.at',
    '%s@onlinebeep.net',
    '%s@optusmobile.com.au',
    // '%s@orange.net',
    // '%s@orangemail.co.in',
    '%s@page.mobilfone.com',
    '%s@page.southernlinc.com',
    '%s@pageme.teletouch.com',
    '%s@pager.irkutsk.ru',
    '%s@pcs.ntelos.com',
    '%s@rek2.com.mx',
    '%s@rpgmail.net',
    '%s@safaricomsms.com',
    '%s@satelindogsm.com',
    '%s@scs-900.ru',
    '%s@sfr.fr',
    '%s@sms.co.tz',
    '%s@sms.comviq.se',
    '%s@sms.emt.ee',
    '%s@sms.goldentele.com',
    '%s@sms.luxgsm.lu',
    '%s@sms.netcom.no',
    // '%s@sms.orange.nl',
    '%s@sms.primtel.ru',
    '%s@sms.t-mobile.at',
    '%s@sms.tele2.lv',
    '%s@sms.umc.com.ua',
    '%s@sms.uraltel.ru',
    '%s@sms.vodafone.it',
    '%s@smsmail.lmt.lv',
    '%s@swmsg.com',
    '%s@t-d1-sms.de',
    '%s@t-mobile-sms.de',
    '%s@t-mobile.uk.net',
    '%s@t.vodafone.ne.jp',
    '%s@text.mtsmobility.com',
    '%s@text.simplefreedom.net',
    '%s@timnet.com',
    '%s@vodafone.net',
    '%s@wyndtell.com',

    // 'sms@pcom.ru (put the number in the subject line)',
    // 'pinnumber@jsmtel.com',
  ],

};
